# Generated by Django 5.2.18 on 2026-10-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('comision', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comercial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
    ]
