# Generated by Django 5.2.18 on 2026-10-10 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PP', 'Pasaporte')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, default='Bogotá', max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Nequi/Daviplata', 'Nequi/Daviplata')], default='Efectivo', max_length=15)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('iva_porcentaje', models.DecimalField(blank=True, decimal_places=2, default=19.0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
