spring.application.name=TiendaDaniel

# 8081 para poder correr al mismo tiempo que AppVentas (8080)
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/tienda
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true

# Muestra el mensaje de error (404, 409...) en el JSON de respuesta
spring.web.error.include-message=always
